//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `GotoPoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <GotoPoint.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompGotoPoint_GotoPoint_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGotoPoint::GotoPoint"
};
const ::std::string iceC_RoboCompGotoPoint_GotoPoint_ops[] =
{
    "atTarget",
    "go",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "stop",
    "turn"
};
const ::std::string iceC_RoboCompGotoPoint_GotoPoint_go_name = "go";
const ::std::string iceC_RoboCompGotoPoint_GotoPoint_turn_name = "turn";
const ::std::string iceC_RoboCompGotoPoint_GotoPoint_stop_name = "stop";
const ::std::string iceC_RoboCompGotoPoint_GotoPoint_atTarget_name = "atTarget";

}

bool
RoboCompGotoPoint::GotoPoint::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGotoPoint_GotoPoint_ids, iceC_RoboCompGotoPoint_GotoPoint_ids + 2, s);
}

::std::vector<::std::string>
RoboCompGotoPoint::GotoPoint::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompGotoPoint_GotoPoint_ids[0], &iceC_RoboCompGotoPoint_GotoPoint_ids[2]);
}

::std::string
RoboCompGotoPoint::GotoPoint::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGotoPoint::GotoPoint::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompGotoPoint::GotoPoint";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_go(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_nodo;
    float iceP_x;
    float iceP_y;
    float iceP_alpha;
    istr->readAll(iceP_nodo, iceP_x, iceP_y, iceP_alpha);
    inS.endReadParams();
    this->go(::std::move(iceP_nodo), iceP_x, iceP_y, iceP_alpha, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_turn(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    float iceP_speed;
    istr->readAll(iceP_speed);
    inS.endReadParams();
    this->turn(iceP_speed, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_stop(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->stop(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_atTarget(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->atTarget(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGotoPoint_GotoPoint_ops, iceC_RoboCompGotoPoint_GotoPoint_ops + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGotoPoint_GotoPoint_ops)
    {
        case 0:
        {
            return _iceD_atTarget(in, current);
        }
        case 1:
        {
            return _iceD_go(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_stop(in, current);
        }
        case 7:
        {
            return _iceD_turn(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGotoPoint::GotoPointPrx::_iceI_go(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_nodo, float iceP_x, float iceP_y, float iceP_alpha, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompGotoPoint_GotoPoint_go_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_nodo, iceP_x, iceP_y, iceP_alpha);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGotoPoint::GotoPointPrx::_iceI_turn(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, float iceP_speed, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompGotoPoint_GotoPoint_turn_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_speed);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGotoPoint::GotoPointPrx::_iceI_stop(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompGotoPoint_GotoPoint_stop_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGotoPoint::GotoPointPrx::_iceI_atTarget(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGotoPoint_GotoPoint_atTarget_name);
    outAsync->invoke(iceC_RoboCompGotoPoint_GotoPoint_atTarget_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompGotoPoint::GotoPointPrx::_newInstance() const
{
    return ::IceInternal::createProxy<GotoPointPrx>();
}
/// \endcond

const ::std::string&
RoboCompGotoPoint::GotoPointPrx::ice_staticId()
{
    return GotoPoint::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompGotoPoint_GotoPoint_go_name = "go";

const ::std::string iceC_RoboCompGotoPoint_GotoPoint_turn_name = "turn";

const ::std::string iceC_RoboCompGotoPoint_GotoPoint_stop_name = "stop";

const ::std::string iceC_RoboCompGotoPoint_GotoPoint_atTarget_name = "atTarget";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompGotoPoint::upCast(GotoPoint* p) { return p; }

void
::IceProxy::RoboCompGotoPoint::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< GotoPoint>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new GotoPoint;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::_iceI_begin_go(const ::std::string& iceP_nodo, ::Ice::Float iceP_x, ::Ice::Float iceP_y, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGotoPoint_GotoPoint_go_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGotoPoint_GotoPoint_go_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_nodo);
        ostr->write(iceP_x);
        ostr->write(iceP_y);
        ostr->write(iceP_alpha);
        result->endWriteParams();
        result->invoke(iceC_RoboCompGotoPoint_GotoPoint_go_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_go(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompGotoPoint_GotoPoint_go_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::_iceI_begin_turn(::Ice::Float iceP_speed, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGotoPoint_GotoPoint_turn_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGotoPoint_GotoPoint_turn_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_speed);
        result->endWriteParams();
        result->invoke(iceC_RoboCompGotoPoint_GotoPoint_turn_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_turn(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompGotoPoint_GotoPoint_turn_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::_iceI_begin_stop(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGotoPoint_GotoPoint_stop_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGotoPoint_GotoPoint_stop_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGotoPoint_GotoPoint_stop_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_stop(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompGotoPoint_GotoPoint_stop_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::_iceI_begin_atTarget(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGotoPoint_GotoPoint_atTarget_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGotoPoint_GotoPoint_atTarget_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGotoPoint_GotoPoint_atTarget_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompGotoPoint_GotoPoint_atTarget_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::RoboCompGotoPoint::GotoPoint::end_atTarget(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGotoPoint_GotoPoint_atTarget_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompGotoPoint::GotoPoint::_newInstance() const
{
    return new GotoPoint;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompGotoPoint::GotoPoint::ice_staticId()
{
    return ::RoboCompGotoPoint::GotoPoint::ice_staticId();
}

RoboCompGotoPoint::GotoPoint::~GotoPoint()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompGotoPoint::upCast(GotoPoint* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompGotoPoint_GotoPoint_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGotoPoint::GotoPoint"
};

}

bool
RoboCompGotoPoint::GotoPoint::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGotoPoint_GotoPoint_ids, iceC_RoboCompGotoPoint_GotoPoint_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompGotoPoint::GotoPoint::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompGotoPoint_GotoPoint_ids[0], &iceC_RoboCompGotoPoint_GotoPoint_ids[2]);
}

const ::std::string&
RoboCompGotoPoint::GotoPoint::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGotoPoint::GotoPoint::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompGotoPoint::GotoPoint";
    return typeId;
#else
    return iceC_RoboCompGotoPoint_GotoPoint_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_go(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_nodo;
    ::Ice::Float iceP_x;
    ::Ice::Float iceP_y;
    ::Ice::Float iceP_alpha;
    istr->read(iceP_nodo);
    istr->read(iceP_x);
    istr->read(iceP_y);
    istr->read(iceP_alpha);
    inS.endReadParams();
    this->go(iceP_nodo, iceP_x, iceP_y, iceP_alpha, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_turn(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Float iceP_speed;
    istr->read(iceP_speed);
    inS.endReadParams();
    this->turn(iceP_speed, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_stop(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->stop(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceD_atTarget(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->atTarget(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompGotoPoint_GotoPoint_all[] =
{
    "atTarget",
    "go",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "stop",
    "turn"
};

}

/// \cond INTERNAL
bool
RoboCompGotoPoint::GotoPoint::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGotoPoint_GotoPoint_all, iceC_RoboCompGotoPoint_GotoPoint_all + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGotoPoint_GotoPoint_all)
    {
        case 0:
        {
            return _iceD_atTarget(in, current);
        }
        case 1:
        {
            return _iceD_go(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_stop(in, current);
        }
        case 7:
        {
            return _iceD_turn(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompGotoPoint::GotoPoint::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< GotoPoint, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompGotoPoint::GotoPoint::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< GotoPoint, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGotoPoint::_icePatchObjectPtr(GotoPointPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = GotoPointPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(GotoPoint::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
